#include <stdio.h>

int main() {
    printf("SAYA BERJANJI AKAN MENGERJAKAN UTSP INI DENGAN JUJUR DAN BERTANGGUNGJAWAB.\n");
    printf("SAYA BERSEDIA MENERIMA SANKSI BERUPA NILAI E MATA KULIAH INI JIKA TERBUKTI MELAKUKAN KECURANGAN.\n");
    return 0;
}